version: "3.4"
services:
  mapisto-api_test:
    build: .
    volumes:
      - ./src:/app/src
    command: pytest
    tty: true
    env_file:
      - conf.test.env
    depends_on: 
      - database
  database:
    image: postgres:12-alpine
    ports: 
      - 5434:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
